/* npm install --no-save playwright; PLAYWRIGHT_BROWSER may point at Edge/Chrome.
   Real browser interaction; fixtures isolate milestones. Full natural progression is in playthrough.cjs. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),KEY='im-zeichen-der-wende:v1';
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_BROWSER?{executablePath:process.env.PLAYWRIGHT_BROWSER}:{})});
 const out=process.env.WENDE_SCREENSHOTS; if(out)fs.mkdirSync(out,{recursive:true});let checks=0;
 const ok=(v,m)=>{assert.ok(v,m);checks++;};
 async function run(touch){const context=await browser.newContext({viewport:touch?{width:1024,height:768}:{width:1440,height:1000},hasTouch:touch,isMobile:touch,deviceScaleFactor:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);const G=await page.evaluate(()=>({scenes:GAME.scenes,seals:GAME.seals,puzzles:GAME.puzzles,notes:GAME.notes,minigames:GAME.minigames}));
 const click=async sel=>touch?await page.locator(sel).tap():await page.locator(sel).click();
 const button=async text=>{const b=page.getByRole('button',{name:text,exact:true});touch?await b.tap():await b.click();};
 const snap=async name=>{if(out)await page.screenshot({path:path.join(out,(touch?'ipad-':'desktop-')+name+'.png'),fullPage:true});};
 const base=scene=>({version:1,started:true,scene,unlocked:G.scenes.map(s=>s.id),inventory:['light','key','scrolls'],solved:Object.keys(G.puzzles).filter(id=>!['timeline','bridge'].includes(id)),seals:G.seals,notes:Object.keys(G.notes).filter(k=>k!=='bridge'),seen:G.scenes.flatMap(s=>['intro:'+s.id,...s.hotspots.map((_,i)=>s.id+':'+i)]),evidence:['scroll','door','church','chain'],drafts:{},hints:{},flags:{archiveScrollsReceived:true,archiveScrollsRead:true,archiveScrollsDeposited:true,sealsPlaced:true},progress:10});
 const load=async s=>{await page.evaluate(([key,s])=>localStorage.setItem(key,JSON.stringify(s)),[KEY,s]);await page.reload();await button('Spiel fortsetzen');};
 const saved=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);
 const noOverflow=async()=>ok(await page.evaluate(()=>{const m=document.querySelector('#modal');return document.documentElement.scrollWidth<=innerWidth&&m.scrollWidth<=m.clientWidth+2;}),'No horizontal overflow');
 await button('Die Stadt betreten');ok(await page.getByRole('button',{name:'Szene erkunden',exact:true}).count()===1,'Entry wording');await button('Szene erkunden');
 await load(base('vestibule'));await click('[data-hotspot="scrolls"]');for(let i=0;i<3;i++){ok(await page.locator('.archive-scroll p').innerText()===await page.evaluate(i=>GAME.texts.archive.body[i],i),'Scroll preserves source '+i);await noOverflow();if(i===0)await snap('scroll');if(i<2)await button('Nächste Schriftrolle');}await button('Gelesen – zum Archiv bringen');
 // Every person uses a single rectangular button for label, backdrop and pointer hit testing.
 for(const id of ['camp','motives','gate','house','forum','office','temple']){await load(base(id));const boxes=await page.locator('.hotspot.person').evaluateAll(nodes=>nodes.map(n=>{const a=n.getBoundingClientRect(),b=n.querySelector('.label').getBoundingClientRect();return {same:Math.abs(a.x-b.x)<1&&Math.abs(a.y-b.y)<1&&Math.abs(a.width-b.width)<1&&Math.abs(a.height-b.height)<1,hit:document.elementFromPoint(a.x+a.width/2,a.y+a.height/2)?.closest('button')===n,height:a.height};}));ok(boxes.every(b=>b.same&&b.hit&&b.height>=44),'Unified person bounds '+id);}
 await load(base('camp'));await click('[data-hotspot="messenger"]');ok(await page.locator('#speech').count()===1,'Messenger touch');await snap('camp');await click('.speech-close');await click('[data-hotspot="map312"]');ok(await page.locator('.bm-stage').count()===1,'Real military map');await click('#close');
 await load(base('motives'));await snap('motives-scene');await click('[data-hotspot="advisor"]');await click('.speech-close');await click('[data-hotspot="motives"]');
 const p=G.minigames.motives;for(let i=0;i<p.cards.length;i++){await click('.wg-card[data-card="'+i+'"]');await click('.mosaic-field[data-target="'+(i===6?2:p.cards[i].ok[0])+'"]');}ok(await page.locator('.mosaic-game.assembled').count()===1,'Mosaic assembled without balancing');ok(await page.locator('.wg-scale,.wg-beam').count()===0,'No scale');await page.waitForTimeout(1650);await page.locator('.motive-relief').scrollIntoViewIfNeeded();await noOverflow();ok(await page.locator('.mosaic-game').evaluate(n=>{const fields=[...n.querySelectorAll('.mosaic-field')],reasons=n.querySelector('.wg-reasons').getBoundingClientRect();return fields.every(f=>[...f.querySelectorAll('.wg-card')].every(c=>c.getBoundingClientRect().bottom<=f.getBoundingClientRect().bottom)&&f.getBoundingClientRect().bottom<reasons.top);}), 'Mosaic cards stay inside fields without covering reasons');await snap('mosaic');await click('.wg-reason[data-k="'+p.reasons.options.findIndex(o=>o.ok)+'"]');await button('Weiter');await click('#close');
 await load(base('basilica'));await click('[data-hotspot="timeline"]');ok((await page.locator('.puzzle-head').innerText()).includes('Notizbuch'),'Notebook in task');await button('Zeitspuren im Notizbuch nachlesen');ok((await page.locator('#modal-content').innerText()).includes('325 und 337'),'Journal retained');await button('Zurück zur Chronikmaschine');
 await click('[data-event="0"]');await click('#slot-0');await button('Mechanismus prüfen');ok(!(await page.locator('.ring-feedback').allTextContents()).join(' ').includes('303 gehört'),'No answer leak');ok((await saved()).flags.timelineAttempts[0]===1,'First element attempt persisted');await click('#close');await click('[data-hotspot="timeline"]');await click('[data-event="0"]');await click('#slot-1');await button('Mechanismus prüfen');ok((await page.locator('[data-ring="1"] .ring-feedback').innerText()).includes('Notizbuch'),'Second attempt follows moved element');
 await click('#puzzle-hint');ok(!(await page.locator('#hint-box').innerText()).includes('Dein Notizbuch enthält'),'First hint adds information');await click('#puzzle-hint');await click('#puzzle-hint');ok(await page.getByRole('button',{name:'Vollständige Zeitfolge zeigen'}).count()===1,'Explicit full help');await button('Vollständige Zeitfolge zeigen');ok((await page.locator('#hint-box').innerText()).includes('303 Verfolgung'),'Requested solution available');
 for(let i=0;i<G.puzzles.timeline.rows.length;i++){await click('[data-event="'+G.puzzles.timeline.rows[i].answer[0]+'"]');await click('#slot-'+i);}await button('Mechanismus prüfen');ok(await page.locator('.year-socket.locked').count()===6,'All six rings locked');await noOverflow();await page.locator('.chronicle-machine').scrollIntoViewIfNeeded();await snap('machine');await page.waitForTimeout(1850);await click('[data-gap="0"]');await button('Zur Argumentationsbrücke');await click('#close');
 await click('[data-hotspot="bridge"]');for(let i=0;i<G.minigames.bridge.arches.length;i++){await click('.ab-plate[data-ok="true"]');await page.waitForTimeout(1550);}for(let i=0;i<G.minigames.bridge.simplify.items.length;i++){if(G.minigames.bridge.simplify.items[i].simple)await click('.ab-plaque[data-k="'+i+'"]');}await page.waitForTimeout(2250);await click('.ab-tablet[data-k="'+G.minigames.bridge.final.options.findIndex(o=>o.ok)+'"]');await page.locator('.finale-stage').waitFor();ok((await saved()).flags.finished,'Final starts only after final main puzzle');await page.waitForTimeout(5500);await snap('finale-opening');await page.waitForTimeout(1800);await snap('finale-memory');await page.waitForTimeout(13000);ok(await page.getByText('Abenteuer abgeschlossen',{exact:true}).isVisible(),'Finite sequence reaches end');await noOverflow();await snap('ending');
 await page.reload();await button('Spiel fortsetzen');ok(await page.getByText('Abenteuer abgeschlossen',{exact:true}).isVisible(),'Completed reload end view');await button('Neues Spiel');ok((await saved()).solved.length===12,'Reset needs confirmation');await button('Abbrechen');await button('Stadt weiter erkunden');ok(!(await page.locator('#modal').evaluate(n=>n.open)),'Explicit exploration');
 // Incomplete fixtures must never open the final puzzle or set finished.
 const incomplete=base('basilica');incomplete.solved=incomplete.solved.filter(x=>x!=='council');incomplete.solved.push('timeline');await load(incomplete);await click('[data-hotspot="bridge"]');ok(await page.getByText('Hier fehlt noch etwas',{exact:true}).isVisible(),'Final guarded against missing main puzzle');ok(!(await saved()).flags.finished,'Missing prerequisites do not finish');
 const finished=base('basilica');finished.solved=Object.keys(G.puzzles);finished.flags.finished=true;await page.emulateMedia({reducedMotion:'reduce'});await load(finished);ok(await page.getByText('Abenteuer abgeschlossen',{exact:true}).isVisible(),'Reduced motion immediate equivalent');ok(await page.locator('.finale-stage').evaluate(n=>n.getAnimations({subtree:true}).length===0),'Reduced motion has no animation');await button('Stadt weiter erkunden');await page.emulateMedia({reducedMotion:'no-preference'});
 // Real archive pointer/touch flow, without the full-playthrough canvas stub.
 const dark=base('archive');dark.solved=dark.solved.filter(id=>id!=='archive');dark.flags.archiveScrollsDeposited=false;await load(dark);
 if(touch)await page.locator('#scene').tap({position:{x:150,y:200}});else await page.locator('#scene').click({position:{x:150,y:200}});
 await button('Lampe hochhalten');const archive=await page.evaluate(()=>GAME.minigames.archive);
 for(let i=0;i<archive.spots.length;i++){const spot=page.locator('.dark-spot').nth(i);if(touch)await spot.tap();else await spot.click();await page.locator('.dark-opts').getByRole('button',{name:archive.measures[archive.spots[i].answer],exact:true}).click();}
 await page.locator('.dark-opts').getByRole('button',{name:archive.final.options[archive.final.answer],exact:true}).click();await button('Weiter');ok((await saved()).solved.includes('archive'),'Real archive solved with pointer/touch');await click('#close');ok(await page.locator('[data-hotspot="archive"]').getAttribute('aria-label')==='Archivmechanismus – gelöst','Clear solved archive name');await click('[data-hotspot="shelf"]');ok((await saved()).flags.archiveScrollsDeposited,'Archive delivery still unlocks next stage');await click('#close');
 // Closing/reopening running minigames must stop their global resources.
 await load(base('forum'));for(let i=0;i<3;i++){await click('[data-hotspot="sources"]');await button('Zuhören');await click('#close');}await page.waitForTimeout(250);ok(errors.length===0,'No browser errors: '+errors.join('; '));await context.close();}
 try{await run(false);await run(true);console.log(JSON.stringify({status:'PASS',checks,browsers:'Chromium desktop and touch 1024×768',physicalIPad:false}));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
