// Optional standalone browser regression: npm install --no-save playwright; npx playwright install chromium
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.woff':'font/woff'})[path.extname(file)]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_BROWSER});try{
for(const [width,height]of [[1024,768],[1180,820],[1366,1024]]){const context=await browser.newContext({viewport:{width,height},hasTouch:true,deviceScaleFactor:2}),page=await context.newPage(),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404)missing.push(r.url());});await page.goto('http://127.0.0.1:'+server.address().port+'/tests/bonus-harness.html');
 for(const id of ['zeichen','katakomben','tiber','bilder','circus']){await page.locator('[data-bonus-start="'+id+'"]').tap();await page.locator('.bonus-introcard .primary').tap();await page.waitForTimeout(100);const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,small:[...document.querySelectorAll('#modal button')].filter(b=>{const r=b.getBoundingClientRect();return r.width>0&&getComputedStyle(b).visibility!=='hidden'&&(r.width<43||r.height<43);}).map(b=>b.textContent),broken:[...document.querySelectorAll('#modal img[src]')].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}));assert.deepEqual(layout,{overflow:false,small:[],broken:[]});
  await page.locator('.bonus-pause').tap();assert(await page.locator('.bonus-pausecard').isVisible());await page.getByRole('button',{name:'Weiterspielen',exact:true}).tap();assert.equal(await page.locator('.bonus-pausecard').count(),0);
  if(id==='katakomben'){await page.getByRole('button',{name:'Nach rechts',exact:true}).tap();await page.getByRole('button',{name:'Nach rechts',exact:true}).tap();await page.locator('[data-answer="1"]').tap();assert((await page.locator('.cat-feedback').innerText()).length>20);await page.locator('[data-answer="0"]').tap();await page.locator('.cat-continue').tap();assert((await page.locator('.cat-progress').innerText()).includes('1 gedeutet'));}
  if(process.env.WENDE_SCREENSHOTS){fs.mkdirSync(process.env.WENDE_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.WENDE_SCREENSHOTS,width+'-'+id+'.png')});}
  await page.locator('.bonus-leave').tap();await page.locator('[data-bonus-start="'+id+'"]').tap();assert(await page.locator('.bonus-introcard').isVisible());await page.locator('.bonus-leave').tap();
 }
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS touch layout, pause, reopen, assets, console:',width,height);await context.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
