'use strict';
(()=>{
 if(!window.BonusGames)return;
 const files={};for(const f of ['floor-straight','wall','symbol-fish','symbol-anchor','inscription','grave-niche','player-up','player-down','player-left','player-right'])files[f]=f+'.png';
 const ART={dir:'assets/bonus/catacombs/',files,available:Object.keys(files)};
 const MAP=['###############','#S....#......E#','#.###.#.#####.#','#...#...#.....#','###.#####.###.#','#...#.....#...#','#.###.###.#.#.#','#.....#...#.#.#','#.#####.###.#.#','#.............#','###############'];
 const CLUES=[
  {x:3,y:1,art:'symbol-fish',title:'Ein Fisch auf Stein',q:'Was ist hier unmittelbar beobachtbar?',answers:['In den Stein ist ein Fischbild eingearbeitet.','Hier trafen sich sicher verfolgte Christen.','Der Stein stammt sicher aus dem Jahr 313.'],correct:0,why:'Beobachtbar ist das Fischbild. Seine religiöse Bedeutung und die Datierung brauchen weitere Hinweise. Ein Fisch allein beweist keine Verfolgung.',reward:'Du füllst deine Lampe auf; dein Lichtkreis wächst.'},
  {x:7,y:3,art:'symbol-anchor',title:'Ein Ankerzeichen',q:'Welche Deutung ist vorsichtig formuliert?',answers:['Hier liegt mit Sicherheit ein Seemann.','Der Anker kann Hoffnung ausdrücken; der Fundzusammenhang entscheidet.','Alle Menschen mit Ankersymbol waren Christen.'],correct:1,why:'Der Anker konnte unter anderem Hoffnung ausdrücken. Ein einzelnes Zeichen beweist weder Beruf noch Glauben einer bestimmten Person.',reward:'Mehr Lampenöl und ein größerer Lichtkreis helfen dir weiter.'},
  {x:5,y:5,art:'inscription',title:'Eine beschädigte Inschrift',q:'Wie gehst du mit den kaum lesbaren Buchstaben um?',answers:['Ich ergänze die Lücken und behandle meine Ergänzung als Tatsache.','Ich kenne dadurch die ganze Lebensgeschichte.','Ich halte Lesbares fest und kennzeichne Ergänzungen als unsicher.'],correct:2,why:'Beobachtung und Ergänzung gehören auseinandergehalten. Beschädigte Buchstaben erlauben keine sichere Lebensgeschichte.',reward:'Die Lampe wird aufgefüllt und leuchtet weiter.'},
  {x:11,y:9,art:'grave-niche',title:'Eine Grabnische',q:'Welche Aussage trägt dieser Befund?',answers:['Die Nische weist auf eine Bestattung hin; regelmäßige Verstecke sind damit nicht belegt.','Alle Christen lebten dauerhaft unter der Erde.','Jede Grabnische beweist eine geheime Versammlung.'],correct:0,why:'Eine Grabnische ist ein Hinweis auf die Nutzung als Begräbnisstätte. Die Behauptung eines dauerhaften Verstecks geht weit darüber hinaus.',reward:'Du erkennst nun den gesamten Grundriss.'}
 ];
 function createModel(){
  const s={x:1,y:1,dir:'down',oil:1,solved:[],found:[],active:null,feedback:'',won:false,visited:new Set(['1,1']),mapped:false};
  const passable=(x,y)=>MAP[y]?.[x]&&MAP[y][x]!=='#';
  function inspect(){const i=CLUES.findIndex(c=>c.x===s.x&&c.y===s.y);if(i>=0&&!s.solved.includes(i)){if(!s.found.includes(i))s.found.push(i);s.active=i;s.feedback='';}}
  function input(dir){if(s.won||s.active!==null)return false;const [dx,dy]=({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[dir]||[0,0];s.dir=dir;if(!passable(s.x+dx,s.y+dy))return false;s.x+=dx;s.y+=dy;s.visited.add(s.x+','+s.y);inspect();if(MAP[s.y][s.x]==='E'){if(s.solved.length>=3)s.won=true;else s.feedback='Am Ausgang fehlen noch sichere Deutungen: Löse mindestens drei Spuren.';}return true;}
  function answer(i){if(s.active===null)return false;const k=s.active,c=CLUES[k];if(i!==c.correct){s.feedback='Prüfe die Sicherheit der Aussage. '+c.why;return false;}if(!s.solved.includes(k)){s.solved.push(k);s.oil=Math.min(1,s.oil+.35);if(k===3)s.mapped=true;}s.feedback=c.why+' '+c.reward;return true;}
  function resume(){if(s.active!==null&&s.solved.includes(s.active)){s.active=null;s.feedback='';}}
  function tick(dt){if(!s.won&&s.active===null)s.oil=Math.max(.25,s.oil-dt/150);}
  return {s,map:MAP,clues:CLUES,passable,input,answer,resume,tick,inspect,radius:()=>2.6+s.oil*1.2+s.solved.length*.35};
 }
 window.BonusGames.register({id:'katakomben',title:'Katakombenlauf',kicker:'Spuren lesen unter der Stadt',art:ART,createModel,
  intro:{text:'Erkunde die unterirdische Begräbnisstätte. Finde vier historische Spuren und unterscheide Beobachtung, plausible Deutung und Spekulation.',controls:['Pfeiltasten antippen oder am PC Pfeiltasten/WASD: ein Schritt.','Auf einer Spur öffnet sich eine kurze Deutungsaufgabe. Fehler darfst du korrigieren.','Richtige Deutungen geben Lampenöl und mehr Sicht. Drei von vier gelösten Spuren öffnen den Ausgang im Nordosten.'],start:'Hinabsteigen'},
  setup(ctx){
   const m=createModel(),imgs=ctx.assets?.(ART)||{},W=600,H=440,T=40;let finished=false,shown=null;
   const root=ctx.layer('cat-game',`<aside class="cat-aside"><h3>Spuren im Dunkeln</h3><p class="cat-progress" role="status"></p><p class="cat-oil"></p><p>Erkunden → Spur finden → deuten → weitergehen.</p><p>Ausgang: im Nordosten.<br>Drei sichere Deutungen öffnen ihn.</p><div class="crossing-pad">${[['up','↑','Nach oben'],['left','←','Nach links'],['down','↓','Nach unten'],['right','→','Nach rechts']].map(([d,a,n])=>`<button type="button" data-dir="${d}" aria-label="${n}">${a}</button>`).join('')}</div><p class="cat-message" role="status"></p></aside><div class="cat-board" role="img" aria-label="Labyrinth mit begrenztem Lampenlicht und vier historischen Spuren"></div>`);
   const board=root.querySelector('.cat-board'),canvas=document.createElement('canvas');board.append(canvas);const g=canvas.getContext('2d');
   const panel=ctx.layer('cat-question');panel.hidden=true;
   function size(){const r=board.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);g.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);}ctx.observe(board,size);
   function renderPanel(){const s=m.s;if(s.active===null){panel.hidden=true;shown=null;return;}panel.hidden=false;const c=m.clues[s.active];if(shown!==s.active){shown=s.active;panel.innerHTML=`<div class="cat-question-inner"><img src="${ART.dir+files[c.art]}" alt="${ctx.esc(c.title)}"><h3>${ctx.esc(c.title)}</h3><p>${ctx.esc(c.q)}</p><div class="cat-options">${c.answers.map((a,i)=>`<button type="button" data-answer="${i}">${ctx.esc(a)}</button>`).join('')}</div><p class="cat-feedback" role="status"></p><button type="button" class="cat-continue" hidden>Weiter erkunden</button></div>`;panel.querySelectorAll('[data-answer]').forEach(b=>ctx.on(b,'click',()=>{if(ctx.paused)return;m.answer(+b.dataset.answer);renderPanel();hud();}));ctx.on(panel.querySelector('.cat-continue'),'click',()=>{if(!ctx.paused){m.resume();renderPanel();}});panel.querySelector('button').focus({preventScroll:true});}
    panel.querySelector('.cat-feedback').textContent=s.feedback;const solved=s.solved.includes(s.active);panel.querySelectorAll('[data-answer]').forEach(b=>b.disabled=solved);panel.querySelector('.cat-continue').hidden=!solved;
   }
   function hud(){root.querySelector('.cat-progress').textContent=`${m.s.found.length} von 4 Spuren gefunden · ${m.s.solved.length} gedeutet`;root.querySelector('.cat-oil').textContent=`Lampenöl: ${Math.round(m.s.oil*100)} %`;root.querySelector('.cat-message').textContent=m.s.active===null?m.s.feedback:'';ctx.setTask(`Spuren: ${m.s.solved.length}/4 gedeutet · ${m.s.solved.length>=3?'Ausgang offen':'3 zum Öffnen nötig'}`);}
   function input(d){if(ctx.running&&!ctx.paused){m.input(d);renderPanel();hud();if(m.s.won&&!finished){finished=true;ctx.win({title:'Mit sicheren Deutungen ans Licht',lines:[`${m.s.solved.length} von 4 Spuren gedeutet.`, 'Du hast Beobachtung, mögliche Deutung und Spekulation unterschieden.']});}}}
   root.querySelectorAll('[data-dir]').forEach(b=>ctx.on(b,'click',()=>input(b.dataset.dir)));ctx.on(document,'keydown',e=>{const d={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'}[e.key];if(d){e.preventDefault();if(!e.repeat)input(d);}});
   function draw(){g.fillStyle='#392b20';g.fillRect(0,0,W,H);for(let y=0;y<11;y++)for(let x=0;x<15;x++){window.BonusArt.draw(g,imgs[MAP[y][x]==='#'?'wall':'floor-straight'],x*T,y*T,T,T);if(MAP[y][x]==='E'){g.fillStyle=m.s.solved.length>=3?'#f7d789':'#a5854b';g.fillRect(x*T+7,y*T+5,26,30);g.fillStyle='#3c2b1d';g.font='bold 23px Georgia';g.textAlign='center';g.fillText('↑',x*T+20,y*T+29);}}
    m.clues.forEach((c,i)=>{window.BonusArt.draw(g,imgs[c.art],c.x*T+4,c.y*T+3,32,34);if(m.s.solved.includes(i)){g.fillStyle='#dbe998';g.font='bold 18px Georgia';g.fillText('✓',c.x*T+30,c.y*T+14);}});
    for(let y=0;y<11;y++)for(let x=0;x<15;x++){const d=Math.hypot(x-m.s.x,y-m.s.y),alpha=Math.min(m.s.mapped?.62:.9,Math.max(0,(d-1.2)/m.radius()));g.fillStyle=`rgba(13,9,6,${alpha})`;g.fillRect(x*T,y*T,T,T);}
    window.BonusArt.draw(g,imgs['player-'+m.s.dir],m.s.x*T+6,m.s.y*T+1,28,38);g.strokeStyle='#f7d88a';g.lineWidth=2;g.strokeRect(m.s.x*T+3,m.s.y*T+2,34,36);
   }
   let elapsed=0;ctx.loop({update(dt){m.tick(dt);elapsed+=dt;if(elapsed>1){hud();elapsed=0;}},draw});return {start(){size();hud();}};
  }
 });
})();
